- menu_name: "Quick Links"

- name: "About Us"
  url: "/about-us"
  title: "About Us"

- name: "Contact"
  url: "/contact/"
  title: "Contact"





# - name: "sitemap.xml"
#   url: "/sitemap.xml"
#   title: "Sitemap for Google Webmaster Tools"

# - name: "RSS"
#   url: "/feed.xml"
#   title: "Subscribe to RSS Feed"

# - name: "Atom"
#   url: "/atom.xml"
#   title: "Subscribe to Atom Feed"


